[project]
name = "direktkreditverwaltung"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altgraph>=0.17.5",
    "asgiref>=3.11.1",
    "chardet>=7.4.3",
    "django>=6.0.6",
    "model-bakery>=1.23.4",
    "packaging>=26.2",
    "pillow>=12.2.0",
    "pyinstaller>=6.20.0",
    "pyinstaller-hooks-contrib>=2026.5",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.3",
    "reportlab>=4.5.1",
    "setuptools>=82.0.1",
    "six>=1.17.0",
    "sqlparse>=0.5.5",
]
